---
apiVersion: v1
kind: Pod
metadata:
  name: spc
  labels:
    env: dev
    app: spc
spec:
  containers:
    name: spc
    image: shaikkhajaibrahim/spcjan2024:1.0
    resources:
     requests:
       cpu: 250m
       memory: 64M
    limits:
       cpu: 500m
       memory: 256M
    ports:
      - containerport: 80
        protocol: TCP