---
apiVersion: v1
kind: Pod
metadata:
  name: sp12
  labels:
    env: Dev
    app: spc
spec:
  containers:
    - name: spcapp
      image: nginx:1.27
      ports:
        - containerPort: 80
    
