apiVersion: v1
kind: Pod
metadata:
  name: spc1
  labels:
    env: dev
    app: spc
spec:
  containers:
    - name: spc
      image: springcommunity/spring-framework-petclinic
      ports:
        - containerPort: 8080
          protocol: TCP